# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Todd's Bistro
description: >- # this means to ignore newlines until "baseurl:"
  A collection of recipes and hand drawn representations of food to accompany them.
  The site also features simple lessons on cooking techniques and shortcuts for people
  who want to cook, but don't have the time to start from scratch.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  recipes:
    output: true
  tips:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      stylesheet: "style.css"
  - 
    scope:
      path: ""
      type: "recipes"
    values:
      title: "Todd's Bistro"
      image-path: "https://s19.postimg.cc/gl8l3go1f/under_construction.jpg"
      stylesheet: "frontpage.css"
      recipe-page: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - README.md
  
host: 0.0.0.0
      